default: &default # All paths are relative to SinatraApp::Application.root
  models_dir: 'app/models'
  controllers_dir: 'app/controllers'
  views_dir: 'app/views'
  lib_dir: 'lib'
  db_dir: 'db'
  log_dir: 'log'
  public_dir: 'public'
  database_config: 'config/database.yml'
  enable_cors_api: false
  enable_api_routing: false
  #Example: { 'v1': { path_prefix: '/', definition: 'api/v1', default: true }, 'v201502': { path_prefix: '/api', definition: 'api201502' } }
  supported_apis: {}

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
