#!/usr/bin/env ruby

require File.expand_path('../../config/environment', __FILE__)

def generate_migration(options = {})
  raise "No model name specified. Example: script/generate_model model_name [fields]" if options[:model].blank?

  migration_name = 'Create' + options[:model].camelize.pluralize
  table_name = options[:model].tableize
  migration = ActiveRecord::Migrator.migrations(SinatraApp::Application.migrations_dir).select{ |m| m.name == migration_name }.first
  raise "Migration already exists at #{SinatraApp::Application.root.join(migration.filename)}" if migration

  filepath = SinatraApp::Application.root.join(SinatraApp::Application.migrations_dir, (Time.now.utc.strftime('%Y%m%d%H%M%S') + '_create_' + table_name + '.rb'))
  puts "Generating migration file #{filepath}"

  File.open(filepath, 'w') do |file|
    file.write <<-MIGRATION
class #{migration_name} < ActiveRecord::Migration
  def change
    create_table :#{table_name} do |t|
      #{options[:fields].map{ |k, v| "t.#{v} :#{k}" }.join("\n      ")}

      t.timestamps null: false
    end
  end
end
    MIGRATION
  end
end

def generate_model(options = {})
  raise "No model name specified. Example: script/generate_model model_name [fields]" if options[:model].blank?
  filepath = SinatraApp::Application.root.join('app/models', (options[:model].downcase.singularize + '.rb'))

  puts "Generating model #{filepath}"
  raise "Model already exists at #{filepath}" if File.exists?(filepath)

  File.open(filepath, 'w') do |file|
    file.write <<-MODEL.strip_heredoc
      class #{options[:model].camelize} < ActiveRecord::Base
      end
    MODEL
  end
end

def parse_options(array)
  options = { :fields => {} }
  options[:model] = ARGV[0].strip if ARGV[0] =~ /^[a-z0-9_]+$/i
  ARGV.shift
  ARGV.each do |arg|
    next unless arg =~ /^[a-z0-9_]+:[a-z0-9_]+$/i
    k, v = arg.split(':').map(&:strip)
    options[:fields][k] = v
  end
  options
end

if __FILE__ == $0
  options = parse_options(ARGV)
  generate_model(options)
  generate_migration(options)
end
